# Generated by Django 5.2 on 2025-05-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='teams/default-profile.jpg', upload_to='teams/%Y/%m/%d/'),
        ),
    ]
